language: node_js
sudo: true

node_js:
  - '12.18'
  - '13.7'
  - '13.14'
  - '14.5'

cache:
  - npm
  - yarn

before_install:
  - git submodule update --init --remote --recursive
  - npm install -g lerna

install:
  - travis_retry make ci-install

script:
  - lerna run tsc
  - yarn run test utils formatters core

after_success:
  - yarn run docs
  - codecov

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
